local L = LibStub("AceLocale-3.0"):NewLocale("ls_Toasts", "enUS", true)

L["Toast Anchor"] = true
L["Toast Title"] = true
L["Appearance Added"] = true
L["Appearance Removed"] = true
L["Toasts in DND mode won't be displayed in combat, but will be queued up in the system instead. Once you leave combat, they'll start popping up."] = true
L["Test"] = true
L["Up"] = true
L["Down"] = true
L["Left"] = true
L["Right"] = true
L["Thome thettings, duh... |cffffd200They are saved per character.|r"] = true
L["Anchor Frame"] = true
L["Appearance"] = true
L["Number of Toasts"] = true
L["Fade Out Delay"] = true
L["Scale"] = true
L["Growth Direction"] = true
L["Colour Names"] = true
L["Colours item, follower names by quality, and world quest, mission titles by rarity."] = true
L["Toasts"] = true
L["Type"] = true
L["Enable"] = true
L["DND"] = true
L["Achievement"] = true
L["Archaeology"] = true
L["Garrison"] = true
L["Dungeon"] = true
L["Loot"] = true
L["Recipe"] = true
L["World Quest"] = true
L["Transmogrification"] = true
L["Settings Transfer"] = true
L["To save current settings as a default preset click the button below. This feature may be quite handy, if you use more or less same layout on many characters. This way you'll need to tweak fewer things. |cffffd200Please note that there can be only 1 preset. Hitting this button on a different character will overwrite existing template.|r"] = true
L["Save Settings"] = true
